# Proxy Configuration for Labor Market Observatory
# This file defines proxy pools and portal-specific strategies

proxy_pools:
  premium:
    description: "High-quality proxies for JS-heavy sites"
    proxies:
      # Working proxies from testing (fastest first)
      - http://124.108.6.20:8085  # 1.15s
      - http://8.221.141.88:3142  # 2.52s
      - http://39.102.209.121:8008  # 2.55s
      - http://41.191.203.162:80  # 2.44s
      - http://8.213.129.15:8081  # 2.53s
    rotation_strategy: "per_request"
    retry_with_new_proxy: true
    max_failures: 3
  
  standard:
    description: "Standard proxies for regular sites"
    proxies:
      # Additional working proxies
      - http://188.166.197.129:3128  # 7.84s
      - http://8.211.51.115:9050  # 7.43s
      - http://51.91.109.83:80  # 10.91s
      - http://103.149.162.194:80
      - http://103.149.162.195:80
    rotation_strategy: "per_page"
    retry_with_new_proxy: true
    max_failures: 5
  
  fallback:
    description: "Fallback proxies when others fail"
    proxies:
      # Backup proxies
      - http://103.149.162.196:80
      - http://103.149.162.197:80
      - http://103.149.162.198:80
    rotation_strategy: "per_request"
    retry_with_new_proxy: false
    max_failures: 10

portal_config:
  elempleo:
    description: "JS-heavy site, requires premium proxies"
    pool: "premium"
    rotation_strategy: "per_request"
    retry_with_new_proxy: true
    timeout: 30
    max_retries: 3
  
  magneto:
    description: "JS-heavy site, requires premium proxies"
    pool: "premium"
    rotation_strategy: "per_request"
    retry_with_new_proxy: true
    timeout: 30
    max_retries: 3
  
  bumeran:
    description: "Selenium-based, standard proxies sufficient"
    pool: "standard"
    rotation_strategy: "per_page"
    retry_with_new_proxy: true
    timeout: 20
    max_retries: 2
  
  zonajobs:
    description: "Selenium-based, standard proxies sufficient"
    pool: "standard"
    rotation_strategy: "per_page"
    retry_with_new_proxy: true
    timeout: 20
    max_retries: 2
  
  clarin:
    description: "Selenium-based, standard proxies sufficient"
    pool: "standard"
    rotation_strategy: "per_page"
    retry_with_new_proxy: true
    timeout: 20
    max_retries: 2
  
  computrabajo:
    description: "Standard Scrapy site, standard proxies sufficient"
    pool: "standard"
    rotation_strategy: "per_request"
    retry_with_new_proxy: true
    timeout: 15
    max_retries: 2
  
  infojobs:
    description: "Standard Scrapy site, standard proxies sufficient"
    pool: "standard"
    rotation_strategy: "per_request"
    retry_with_new_proxy: true
    timeout: 15
    max_retries: 2
  
  occmundial:
    description: "Standard Scrapy site, standard proxies sufficient"
    pool: "standard"
    rotation_strategy: "per_request"
    retry_with_new_proxy: true
    timeout: 15
    max_retries: 2
  
  hiring_cafe:
    description: "API-based site, standard proxies sufficient"
    pool: "standard"
    rotation_strategy: "per_request"
    retry_with_new_proxy: true
    timeout: 15
    max_retries: 2

global_settings:
  default_pool: "standard"
  default_rotation: "per_request"
  default_timeout: 20
  default_max_retries: 3
  health_check_interval: 300  # 5 minutes
  proxy_failure_threshold: 5
  automatic_fallback: true
  log_proxy_usage: true
